import { Listing, OffMarketLead } from "./types";

function scoreListing(l: Partial<Listing>): Listing["scoreBreakdown"] {
  let revenueScore = 0;
  if (l.revenue && l.revenue >= 1_000_000 && l.revenue <= 3_000_000) revenueScore = 25;
  else if (l.revenue && l.revenue >= 500_000 && l.revenue < 1_000_000) revenueScore = 15;
  else if (l.revenue && l.revenue > 3_000_000 && l.revenue <= 5_000_000) revenueScore = 18;
  else revenueScore = 5;

  let marginScore = 0;
  if (l.ebitdaMargin && l.ebitdaMargin >= 15 && l.ebitdaMargin <= 25) marginScore = 20;
  else if (l.ebitdaMargin && l.ebitdaMargin >= 10) marginScore = 12;
  else marginScore = 5;

  let multipleScore = 0;
  if (l.multiple && l.multiple >= 2.5 && l.multiple <= 4.5) multipleScore = 20;
  else if (l.multiple && l.multiple < 2.5) multipleScore = 18;
  else multipleScore = 5;

  let locationScore = 0;
  const nycStates = ["NY", "NJ", "CT"];
  if (l.state && nycStates.includes(l.state)) locationScore = 15;
  else locationScore = 3;

  let recurringScore = 0;
  if (l.recurringRevenuePct && l.recurringRevenuePct >= 70) recurringScore = 10;
  else if (l.recurringRevenuePct && l.recurringRevenuePct >= 50) recurringScore = 6;
  else recurringScore = 2;

  const currentYear = 2026;
  const age = l.yearEstablished ? currentYear - l.yearEstablished : 0;
  let ageScore = 0;
  if (age >= 15) ageScore = 10;
  else if (age >= 8) ageScore = 7;
  else ageScore = 3;

  const total = revenueScore + marginScore + multipleScore + locationScore + recurringScore + ageScore;
  return { revenueScore, marginScore, multipleScore, locationScore, recurringScore, ageScore, total };
}

const rawListings: Omit<Listing, "score" | "scoreBreakdown" | "revenueMultiple">[] = [
  {
    id: "bbs-001",
    name: "Premier Pest Solutions LLC",
    source: "bizbuysell",
    askingPrice: 2_800_000,
    revenue: 1_850_000,
    cashFlow: 370_000,
    ebitdaMargin: 20,
    multiple: 3.8,
    location: "Bergen County, NJ",
    state: "NJ",
    employees: 14,
    yearEstablished: 2005,
    recurringRevenuePct: 82,
    ownerInvolved: true,
    description: "Well-established residential pest control company serving Bergen, Passaic, and Essex counties. 1,400+ recurring accounts, quarterly service model. Owner willing to stay 12 months for transition. Fleet of 8 wrapped vehicles. Strong Google reviews (4.8 stars, 340+ reviews).",
    url: "https://www.bizbuysell.com/Business-Opportunity/pest-control-bergen-county-nj/2437891/",
    dateFound: "2026-03-15",
    status: "reviewing",
    tags: ["SBA eligible", "strong recurring", "owner transition"],
  },
  {
    id: "bbs-002",
    name: "Tri-State Exterminating Corp",
    source: "bizbuysell",
    askingPrice: 4_200_000,
    revenue: 2_900_000,
    cashFlow: 520_000,
    ebitdaMargin: 18,
    multiple: 4.0,
    location: "Westchester County, NY",
    state: "NY",
    employees: 22,
    yearEstablished: 1998,
    recurringRevenuePct: 75,
    ownerInvolved: true,
    description: "Regional pest control operator covering Westchester, Rockland, and Putnam counties. Mix of residential (70%) and light commercial (30%). Includes termite division with annual renewal book worth $180K. Owner is 67, looking for clean exit.",
    url: "https://www.bizbuysell.com/Business-Opportunity/pest-control-westchester-ny/2431205/",
    dateFound: "2026-03-10",
    status: "new",
    tags: ["termite division", "aging owner", "platform candidate"],
  },
  {
    id: "tw-001",
    name: "SafeHome Pest Management",
    source: "transworld",
    askingPrice: 1_600_000,
    revenue: 1_100_000,
    cashFlow: 242_000,
    ebitdaMargin: 22,
    multiple: 3.3,
    location: "Fairfield County, CT",
    state: "CT",
    employees: 9,
    yearEstablished: 2010,
    recurringRevenuePct: 88,
    ownerInvolved: true,
    description: "Highly profitable residential pest control operation in affluent Fairfield County. 900+ recurring customers on quarterly plans. Strong brand recognition, premium pricing ($65/mo avg). Modern tech stack with PestRoutes CRM. Owner (age 62) wants to retire.",
    url: "https://www.tworld.com/listings/pest-control-fairfield-ct-NR29471",
    dateFound: "2026-03-18",
    status: "new",
    tags: ["high margin", "premium market", "tech-enabled", "platform candidate"],
  },
  {
    id: "sb-001",
    name: "Northeast Pest Pros",
    source: "sunbelt",
    askingPrice: 3_500_000,
    revenue: 2_400_000,
    cashFlow: 430_000,
    ebitdaMargin: 17.9,
    multiple: 4.1,
    location: "Nassau County, NY",
    state: "NY",
    employees: 18,
    yearEstablished: 2001,
    recurringRevenuePct: 71,
    ownerInvolved: true,
    description: "Long Island-based pest control company with strong presence in Nassau and Suffolk counties. 1,800 recurring residential accounts plus property management contracts. Includes wildlife exclusion division. Two locations.",
    url: "https://www.sunbeltnetwork.com/business-for-sale/pest-control-nassau-county-ny-118294",
    dateFound: "2026-03-08",
    status: "contacted",
    tags: ["multi-location", "Long Island", "wildlife division"],
  },
  {
    id: "bbs-003",
    name: "Metro Bug Guard Inc",
    source: "bizbuysell",
    askingPrice: 950_000,
    revenue: 680_000,
    cashFlow: 136_000,
    ebitdaMargin: 20,
    multiple: 3.5,
    location: "Middlesex County, NJ",
    state: "NJ",
    employees: 6,
    yearEstablished: 2013,
    recurringRevenuePct: 65,
    ownerInvolved: true,
    description: "Growing pest control company in central NJ. Good customer reviews, expanding customer base. Would make excellent tuck-in acquisition for NJ platform. Owner relocating out of state.",
    url: "https://www.bizbuysell.com/Business-Opportunity/pest-control-middlesex-nj/2445102/",
    dateFound: "2026-03-20",
    status: "new",
    tags: ["tuck-in candidate", "affordable", "motivated seller"],
  },
  {
    id: "bbs-004",
    name: "Guardian Pest Control Services",
    source: "bizbuysell",
    askingPrice: 5_800_000,
    revenue: 4_100_000,
    cashFlow: 615_000,
    ebitdaMargin: 15,
    multiple: 4.7,
    location: "Queens, NY",
    state: "NY",
    employees: 30,
    yearEstablished: 1992,
    recurringRevenuePct: 60,
    ownerInvolved: false,
    description: "Large urban pest control operation. Heavy commercial focus (55% commercial). High revenue but elevated multiple and lower recurring %. Would need operational improvements to hit target margins. Absentee owner.",
    url: "https://www.bizbuysell.com/Business-Opportunity/pest-control-queens-ny/2418733/",
    dateFound: "2026-03-05",
    status: "passed",
    tags: ["overpriced", "commercial heavy", "urban"],
  },
  {
    id: "tw-002",
    name: "Connecticut Critter Control",
    source: "transworld",
    askingPrice: 2_100_000,
    revenue: 1_500_000,
    cashFlow: 315_000,
    ebitdaMargin: 21,
    multiple: 3.3,
    location: "New Haven County, CT",
    state: "CT",
    employees: 11,
    yearEstablished: 2007,
    recurringRevenuePct: 78,
    ownerInvolved: true,
    description: "Well-run residential pest control in New Haven and Hartford counties. Strong termite renewal book ($95K/yr). 1,100 active recurring customers. Owner (64) willing to carry 15% seller note. Clean financials, CPA-reviewed.",
    url: "https://www.tworld.com/listings/pest-control-new-haven-ct-NR30182",
    dateFound: "2026-03-12",
    status: "reviewing",
    tags: ["seller financing", "clean books", "termite upsell"],
  },
  {
    id: "bbs-005",
    name: "All Seasons Pest Elimination",
    source: "bizbuysell",
    askingPrice: 1_200_000,
    revenue: 920_000,
    cashFlow: 175_000,
    ebitdaMargin: 19,
    multiple: 3.4,
    location: "Morris County, NJ",
    state: "NJ",
    employees: 7,
    yearEstablished: 2011,
    recurringRevenuePct: 73,
    ownerInvolved: true,
    description: "Residential-focused pest control in affluent Morris County suburbs. 750 recurring customers. Strong reputation with 4.7 Google rating. Newer fleet (2022-2024 vehicles). Owner health issues motivating sale.",
    url: "https://www.bizbuysell.com/Business-Opportunity/pest-control-morris-county-nj/2449817/",
    dateFound: "2026-03-22",
    status: "new",
    tags: ["motivated seller", "affluent market", "newer fleet"],
  },
  {
    id: "sb-002",
    name: "Hudson Valley Pest Management",
    source: "sunbelt",
    askingPrice: 1_900_000,
    revenue: 1_350_000,
    cashFlow: 270_000,
    ebitdaMargin: 20,
    multiple: 3.5,
    location: "Orange County, NY",
    state: "NY",
    employees: 10,
    yearEstablished: 2008,
    recurringRevenuePct: 80,
    ownerInvolved: true,
    description: "Solid residential pest control serving Orange, Dutchess, and Ulster counties. Growing market with new housing developments. 1,050 recurring accounts. Modern CRM. Owner (59) exploring options but not in a rush.",
    url: "https://www.sunbeltnetwork.com/business-for-sale/pest-control-orange-county-ny-119847",
    dateFound: "2026-03-14",
    status: "new",
    tags: ["growing market", "good systems", "patient seller"],
  },
  {
    id: "ln-001",
    name: "Precision Pest NYC",
    source: "loopnet",
    askingPrice: 3_200_000,
    revenue: 2_200_000,
    cashFlow: 396_000,
    ebitdaMargin: 18,
    multiple: 4.0,
    location: "Brooklyn, NY",
    state: "NY",
    employees: 16,
    yearEstablished: 2003,
    recurringRevenuePct: 68,
    ownerInvolved: true,
    description: "Brooklyn-based pest control with strong presence in Brooklyn, Staten Island, and parts of NJ. Mix of residential (65%) and commercial (35%). Includes bed bug heat treatment specialty. Owner wants to sell within 6 months.",
    url: "https://www.loopnet.com/biz/pest-control-brooklyn-ny/B0847231/",
    dateFound: "2026-03-19",
    status: "new",
    tags: ["bed bug specialty", "urgent timeline", "cross-state"],
  },
];

export const listings: Listing[] = rawListings.map((l) => {
  const breakdown = scoreListing(l);
  const revenueMultiple = +(l.askingPrice / l.revenue).toFixed(2);
  return { ...l, revenueMultiple, score: breakdown.total, scoreBreakdown: breakdown } as Listing;
});

export const offMarketLeads: OffMarketLead[] = [
  {
    id: "om-001",
    businessName: "ABC Pest Control",
    ownerName: "Robert Marinelli",
    phone: "(201) 555-0142",
    address: "847 Main St",
    city: "Hackensack",
    state: "NJ",
    rating: 4.6,
    reviewCount: 187,
    yearsInBusiness: 28,
    estimatedRevenue: "$1.2M-$1.8M",
    ownerAge: "65+",
    source: "google_maps",
    outreachStatus: "not_contacted",
    notes: "Long-established business, family-run. Website hasn't been updated since 2019. Classic succession candidate.",
    lastUpdated: "2026-03-20",
    priorityScore: 92,
  },
  {
    id: "om-002",
    businessName: "Reliable Exterminating Co",
    ownerName: "Frank DeLuca",
    phone: "(914) 555-0198",
    address: "1220 Central Park Ave",
    city: "Yonkers",
    state: "NY",
    rating: 4.4,
    reviewCount: 253,
    yearsInBusiness: 35,
    estimatedRevenue: "$2.0M-$2.8M",
    ownerAge: "70+",
    source: "google_maps",
    outreachStatus: "contacted",
    notes: "High review volume indicates large customer base. Business established 1991. No succession plan visible. Second-generation owner nearing retirement.",
    lastUpdated: "2026-03-18",
    priorityScore: 95,
  },
  {
    id: "om-003",
    businessName: "Garden State Bug Busters",
    ownerName: "Anthony Russo",
    phone: "(973) 555-0167",
    address: "56 Bloomfield Ave",
    city: "Montclair",
    state: "NJ",
    rating: 4.8,
    reviewCount: 312,
    yearsInBusiness: 22,
    estimatedRevenue: "$1.5M-$2.2M",
    ownerAge: "60+",
    source: "license_db",
    outreachStatus: "responded",
    notes: "Found via NJ DEP pesticide license database. License holder since 2004. High Google rating in affluent market. Responded positively to initial outreach - interested in discussing options.",
    lastUpdated: "2026-03-22",
    priorityScore: 97,
  },
  {
    id: "om-004",
    businessName: "Stamford Pest Solutions",
    ownerName: "William Chen",
    phone: "(203) 555-0134",
    address: "199 Atlantic St",
    city: "Stamford",
    state: "CT",
    rating: 4.5,
    reviewCount: 145,
    yearsInBusiness: 18,
    estimatedRevenue: "$800K-$1.2M",
    ownerAge: "55-60",
    source: "association",
    outreachStatus: "not_contacted",
    notes: "Found via CT Pest Control Association membership directory. Active member since 2008. Smaller operation but excellent location for CT market entry.",
    lastUpdated: "2026-03-19",
    priorityScore: 78,
  },
  {
    id: "om-005",
    businessName: "Borough Pest Management",
    ownerName: "James O'Brien",
    phone: "(718) 555-0156",
    address: "3421 Broadway",
    city: "Bronx",
    state: "NY",
    rating: 4.3,
    reviewCount: 98,
    yearsInBusiness: 31,
    estimatedRevenue: "$900K-$1.4M",
    ownerAge: "65+",
    source: "google_maps",
    outreachStatus: "not_contacted",
    notes: "Urban specialist. Long tenure suggests stable customer base. Lower review count may indicate less tech-savvy owner (opportunity for modernization). Website is basic HTML from early 2000s.",
    lastUpdated: "2026-03-21",
    priorityScore: 84,
  },
  {
    id: "om-006",
    businessName: "Suburban Shield Pest Co",
    ownerName: "Thomas Kowalski",
    phone: "(516) 555-0189",
    address: "2100 Hempstead Tpke",
    city: "East Meadow",
    state: "NY",
    rating: 4.7,
    reviewCount: 224,
    yearsInBusiness: 25,
    estimatedRevenue: "$1.8M-$2.5M",
    ownerAge: "60+",
    source: "google_maps",
    outreachStatus: "meeting_set",
    notes: "Large Long Island operation. High review count and rating. Found through Google Maps scrape - website mentions 'family owned since 2001'. Meeting scheduled for March 28.",
    lastUpdated: "2026-03-23",
    priorityScore: 94,
  },
  {
    id: "om-007",
    businessName: "Pro-Tech Pest Elimination",
    ownerName: "Michael Santoro",
    phone: "(908) 555-0143",
    address: "789 Route 22",
    city: "Bridgewater",
    state: "NJ",
    rating: 4.2,
    reviewCount: 167,
    yearsInBusiness: 20,
    estimatedRevenue: "$1.0M-$1.5M",
    ownerAge: "60+",
    source: "referral",
    outreachStatus: "contacted",
    notes: "Referred by SBA lender contact. Owner has mentioned retirement plans at industry events. Central NJ location good for route density with existing NJ targets.",
    lastUpdated: "2026-03-17",
    priorityScore: 88,
  },
  {
    id: "om-008",
    businessName: "Valley Pest Professionals",
    ownerName: "Richard Patel",
    phone: "(845) 555-0172",
    address: "445 Route 9W",
    city: "Newburgh",
    state: "NY",
    rating: 4.5,
    reviewCount: 89,
    yearsInBusiness: 15,
    estimatedRevenue: "$600K-$900K",
    ownerAge: "55-60",
    source: "google_maps",
    outreachStatus: "not_interested",
    notes: "Hudson Valley operator. Responded to outreach but says not interested in selling at this time. Worth following up in 6-12 months.",
    lastUpdated: "2026-03-15",
    priorityScore: 55,
  },
];
