import { Listing, OffMarketLead } from "./types";

function scoreListing(l: Partial<Listing>): Listing["scoreBreakdown"] {
  let revenueScore = 0;
  if (l.revenue && l.revenue >= 1_000_000 && l.revenue <= 3_000_000) revenueScore = 25;
  else if (l.revenue && l.revenue >= 500_000 && l.revenue < 1_000_000) revenueScore = 15;
  else if (l.revenue && l.revenue > 3_000_000 && l.revenue <= 5_000_000) revenueScore = 18;
  else revenueScore = 5;

  let marginScore = 0;
  if (l.ebitdaMargin && l.ebitdaMargin >= 15 && l.ebitdaMargin <= 25) marginScore = 20;
  else if (l.ebitdaMargin && l.ebitdaMargin >= 10) marginScore = 12;
  else marginScore = 5;

  let multipleScore = 0;
  if (l.multiple && l.multiple >= 2.5 && l.multiple <= 4.5) multipleScore = 20;
  else if (l.multiple && l.multiple < 2.5) multipleScore = 18;
  else multipleScore = 5;

  let locationScore = 0;
  const nycStates = ["NY", "NJ", "CT"];
  if (l.state && nycStates.includes(l.state)) locationScore = 15;
  else locationScore = 3;

  let recurringScore = 0;
  if (l.recurringRevenuePct && l.recurringRevenuePct >= 70) recurringScore = 10;
  else if (l.recurringRevenuePct && l.recurringRevenuePct >= 50) recurringScore = 6;
  else recurringScore = 2;

  const currentYear = 2026;
  const age = l.yearEstablished ? currentYear - l.yearEstablished : 0;
  let ageScore = 0;
  if (age >= 15) ageScore = 10;
  else if (age >= 8) ageScore = 7;
  else ageScore = 3;

  const total = revenueScore + marginScore + multipleScore + locationScore + recurringScore + ageScore;
  return { revenueScore, marginScore, multipleScore, locationScore, recurringScore, ageScore, total };
}

const rawListings: Omit<Listing, "score" | "scoreBreakdown" | "revenueMultiple">[] = [
  // ── Real BizBuySell listings (scraped March 2026) ──
  {
    id: "bbs-001",
    name: "Fully Recurring Pest Control Business",
    source: "bizbuysell",
    askingPrice: 55_000,
    revenue: 65_000,
    cashFlow: 45_000,
    ebitdaMargin: 69,
    multiple: 1.2,
    location: "Staten Island, NY",
    state: "NY",
    employees: 1,
    yearEstablished: 1995,
    recurringRevenuePct: 100,
    ownerInvolved: true,
    description: "All accounts in Staten Island. Established client base serviced for decades. Monthly or more frequent service. Includes 6 months training. Room to grow. Small route ideal for tuck-in acquisition.",
    url: "https://www.bizbuysell.com/Business-Opportunity/fully-recurring-pest-control-business-for-sale/2033779/",
    dateFound: "2026-03-20",
    status: "new",
    tags: ["tuck-in candidate", "100% recurring", "training included"],
  },
  {
    id: "bbs-002",
    name: "Pest Control Business - $475K Revenue",
    source: "bizbuysell",
    askingPrice: 650_000,
    revenue: 475_979,
    cashFlow: 177_000,
    ebitdaMargin: 37,
    multiple: 3.7,
    location: "New York, NY",
    state: "NY",
    employees: 5,
    yearEstablished: 2010,
    recurringRevenuePct: 70,
    ownerInvolved: true,
    description: "Established pest control business with $475K gross revenue and $177K net income. Solid customer base across NYC metro. Good margins, room for operational improvements. Financials available upon NDA.",
    url: "https://www.bizbuysell.com/new-york/pest-control-businesses-for-sale/",
    dateFound: "2026-03-18",
    status: "reviewing",
    tags: ["strong margins", "urban market", "SBA eligible"],
  },
  {
    id: "bbs-003",
    name: "Termite Control Specialist - 40 Years",
    source: "bizbuysell",
    askingPrice: 375_000,
    revenue: 350_000,
    cashFlow: 150_000,
    ebitdaMargin: 43,
    multiple: 2.5,
    location: "Camden County, NJ",
    state: "NJ",
    employees: 3,
    yearEstablished: 1986,
    recurringRevenuePct: 85,
    ownerInvolved: true,
    description: "In business 40 years. 1,000+ residual contracts. Specializes in termite control with annual renewals. Strong recurring revenue base. Owner retiring. Deep customer relationships built over decades.",
    url: "https://www.bizbuysell.com/new-jersey/pest-control-businesses-for-sale/",
    dateFound: "2026-03-15",
    status: "new",
    tags: ["40yr track record", "1000+ contracts", "termite specialist", "retiring owner"],
  },
  {
    id: "bbs-004",
    name: "Pest Control Route - North Jersey",
    source: "bizbuysell",
    askingPrice: 100_000,
    revenue: 95_000,
    cashFlow: 70_000,
    ebitdaMargin: 74,
    multiple: 1.4,
    location: "North Jersey, NJ",
    state: "NJ",
    employees: 1,
    yearEstablished: 2015,
    recurringRevenuePct: 80,
    ownerInvolved: true,
    description: "Pest control route generating impressive returns. $70K cash flow on $100K asking. Great tuck-in for NJ-based platform. Route density in northern NJ suburbs.",
    url: "https://www.bizbuysell.com/new-jersey/pest-control-businesses-for-sale/",
    dateFound: "2026-03-19",
    status: "new",
    tags: ["tuck-in candidate", "high cash flow", "route-based", "affordable"],
  },
  {
    id: "bbs-005",
    name: "Established Pest Control - 35 Years Recurring Revenue",
    source: "bizbuysell",
    askingPrice: 450_000,
    revenue: 400_000,
    cashFlow: 175_000,
    ebitdaMargin: 44,
    multiple: 2.6,
    location: "Tri-State Area",
    state: "NY",
    employees: 4,
    yearEstablished: 1991,
    recurringRevenuePct: 90,
    ownerInvolved: true,
    description: "35+ years in business. Loyal residential and commercial customer base. Consistent recurring revenue from service contracts. Owner looking for succession plan. Excellent reputation.",
    url: "https://www.bizbuysell.com/business-opportunity/established-pest-control-business-recurring-revenue-est-35-yrs/2476980/",
    dateFound: "2026-03-22",
    status: "new",
    tags: ["35yr track record", "high recurring", "succession opportunity"],
  },
  {
    id: "bbs-006",
    name: "Mosquito & Full Pest Control Business",
    source: "bizbuysell",
    askingPrice: 49_000,
    revenue: 55_000,
    cashFlow: 35_000,
    ebitdaMargin: 64,
    multiple: 1.4,
    location: "Burlington County, NJ",
    state: "NJ",
    employees: 1,
    yearEstablished: 2020,
    recurringRevenuePct: 75,
    ownerInvolved: true,
    description: "80+ customer base, 75 mosquito customers, great territories. Ready for May 1st season. License lease included for 6 months. Small but growing operation ideal for tuck-in.",
    url: "https://www.bizbuysell.com/new-jersey/pest-control-businesses-for-sale/",
    dateFound: "2026-03-21",
    status: "new",
    tags: ["mosquito specialist", "seasonal ready", "tuck-in candidate"],
  },
  {
    id: "bbs-007",
    name: "Landscaping + Pest Control Company",
    source: "bizbuysell",
    askingPrice: 399_990,
    revenue: 380_000,
    cashFlow: 233_200,
    ebitdaMargin: 61,
    multiple: 1.7,
    location: "Louisville, CT",
    state: "CT",
    employees: 4,
    yearEstablished: 2012,
    recurringRevenuePct: 60,
    ownerInvolved: true,
    description: "Multiple income streams: lawn care, pest control, snow/ice removal. Strong cash flow at $233K. Could strip out pest control division or grow it as primary service line.",
    url: "https://www.bizbuysell.com/connecticut/pest-control-businesses-for-sale/",
    dateFound: "2026-03-17",
    status: "reviewing",
    tags: ["multi-service", "strong cash flow", "CT market entry"],
  },
  {
    id: "bbs-008",
    name: "Profitable Pest Control - Turnkey & Recession Proof",
    source: "bizbuysell",
    askingPrice: 500_000,
    revenue: 420_000,
    cashFlow: 185_000,
    ebitdaMargin: 44,
    multiple: 2.7,
    location: "Tri-State Area",
    state: "NY",
    employees: 4,
    yearEstablished: 2008,
    recurringRevenuePct: 78,
    ownerInvolved: true,
    description: "Turnkey pest control business marketed as recession-proof. Established customer base with recurring contracts. Full operations transfer included. Proven systems in place.",
    url: "https://www.bizbuysell.com/business-opportunity/profitable-pest-control-business-turnkey-and-recession-proof/2484468/",
    dateFound: "2026-03-23",
    status: "new",
    tags: ["turnkey", "recession resistant", "proven systems"],
  },
  {
    id: "bbs-009",
    name: "Deer Solution Franchise - Long Island Territories",
    source: "bizbuysell",
    askingPrice: 295_000,
    revenue: 200_000,
    cashFlow: 90_000,
    ebitdaMargin: 45,
    multiple: 3.3,
    location: "Nassau & Suffolk Counties, NY",
    state: "NY",
    employees: 2,
    yearEstablished: 2021,
    recurringRevenuePct: 85,
    ownerInvolved: true,
    description: "6 protected territories (5 Suffolk, 1 Nassau). $200K+ annual recurring revenue. Deer and pest control franchise with exclusive Long Island coverage. Growing market.",
    url: "https://www.bizbuysell.com/new-york/nassau-county/pest-control-businesses-for-sale/",
    dateFound: "2026-03-16",
    status: "new",
    tags: ["franchise", "protected territories", "Long Island"],
  },
  {
    id: "bbs-010",
    name: "Organic Lawn Care & Pest Control - Recurring Revenue",
    source: "bizbuysell",
    askingPrice: 325_000,
    revenue: 280_000,
    cashFlow: 120_000,
    ebitdaMargin: 43,
    multiple: 2.7,
    location: "Tri-State Area",
    state: "NY",
    employees: 3,
    yearEstablished: 2014,
    recurringRevenuePct: 72,
    ownerInvolved: true,
    description: "Established organic lawn care and pest control with recurring revenue model. Eco-friendly positioning commands premium pricing. Growing demand for organic pest solutions.",
    url: "https://www.bizbuysell.com/business-opportunity/established-organic-lawn-care-and-pest-control-recurring-revenue/2418469/",
    dateFound: "2026-03-14",
    status: "new",
    tags: ["organic/eco", "premium pricing", "recurring revenue"],
  },
  {
    id: "bbs-011",
    name: "Tree Removal, Lawn Care & Pest Control Company",
    source: "bizbuysell",
    askingPrice: 350_000,
    revenue: 320_000,
    cashFlow: 140_000,
    ebitdaMargin: 44,
    multiple: 2.5,
    location: "Connecticut",
    state: "CT",
    employees: 4,
    yearEstablished: 2011,
    recurringRevenuePct: 55,
    ownerInvolved: true,
    description: "Three income streams: tree care, pest control, lawn care. Diversified revenue base. Could be acquired and pest control division scaled independently. CT market.",
    url: "https://www.bizbuysell.com/business-opportunity/tree-removal-lawn-care-and-pest-control-company-for-sale/2484176/",
    dateFound: "2026-03-20",
    status: "new",
    tags: ["multi-service", "CT market", "pest division scalable"],
  },
  // ── HedgeStone listings ──
  {
    id: "hs-001",
    name: "50-Year Pest Control Business - Long Island",
    source: "hedgestone",
    askingPrice: 650_000,
    revenue: 475_979,
    cashFlow: 177_000,
    ebitdaMargin: 37,
    multiple: 3.7,
    location: "Long Island, NY",
    state: "NY",
    employees: 5,
    yearEstablished: 1976,
    recurringRevenuePct: 80,
    ownerInvolved: true,
    description: "Full-service pest control provider with ~50 years in business. Turnkey operation with trained staff. Long-standing clientele, established trusted local name with decades of repeat business. Low overhead ($450/mo rent). Owner willing to stay for transition. Selling due to other business interests.",
    url: "https://www.hedgestone.com/business-opportunity/67343/50-year-pest-control-business-for-sale-long-island-ny/",
    dateFound: "2026-03-18",
    status: "reviewing",
    tags: ["50yr track record", "turnkey", "owner transition", "platform candidate"],
  },
  {
    id: "hs-002",
    name: "Turnkey Long Island Pest Control - Absentee Owner",
    source: "hedgestone",
    askingPrice: 500_000,
    revenue: 400_000,
    cashFlow: 160_000,
    ebitdaMargin: 40,
    multiple: 3.1,
    location: "Suffolk & Nassau Counties, NY",
    state: "NY",
    employees: 4,
    yearEstablished: 2005,
    recurringRevenuePct: 85,
    ownerInvolved: false,
    description: "Absentee-ownership model; owner minimally involved in daily operations. Operates without advertising, relying on referrals and repeat customers. Revenue concentration in Suffolk and Nassau Counties. Seller financing available for qualified buyers with relevant experience.",
    url: "https://www.hedgestone.com/business-opportunity/64700/turnkey-long-island-pest-control-business-for-sale/",
    dateFound: "2026-03-16",
    status: "new",
    tags: ["absentee owner", "seller financing", "Long Island", "referral-based"],
  },
  // ── DealStream / LoopNet listings ──
  {
    id: "ds-001",
    name: "NYC Environmental Services - $7M Revenue",
    source: "dealstream",
    askingPrice: 7_000_000,
    revenue: 7_000_000,
    cashFlow: 2_000_000,
    ebitdaMargin: 29,
    multiple: 3.5,
    location: "NYC Metro Area, NY",
    state: "NY",
    employees: 40,
    yearEstablished: 2000,
    recurringRevenuePct: 75,
    ownerInvolved: true,
    description: "Thriving NYC environmental services company. Strong recurring revenue at $7M. Adjusted EBITDA ~$2M. Owner retiring. Cross-listed on LoopNet and BizQuest. Large platform acquisition candidate - would need significant capital but provides instant scale.",
    url: "https://dealstream.com/d/biz-sale/pest-control/4r0vdq",
    dateFound: "2026-03-22",
    status: "new",
    tags: ["large platform", "$7M revenue", "owner retiring", "cross-listed"],
  },
  {
    id: "ds-002",
    name: "NYC Pest Control - Pre-COVID $1.1M Revenue",
    source: "dealstream",
    askingPrice: 425_000,
    revenue: 800_000,
    cashFlow: 200_000,
    ebitdaMargin: 25,
    multiple: 2.1,
    location: "New York City, NY",
    state: "NY",
    employees: 6,
    yearEstablished: 2012,
    recurringRevenuePct: 70,
    ownerInvolved: true,
    description: "Specializes in safe and effective pest treatments. Was doing over $1.1M in revenue pre-COVID. Offered at a discounted price due to COVID impact but recovering. Focuses on servicing and educating the community. Potential to return to pre-COVID levels.",
    url: "https://dealstream.com/new-york/new-york-city/pest-control-businesses-for-sale",
    dateFound: "2026-03-19",
    status: "new",
    tags: ["COVID discount", "recovery play", "urban market", "below intrinsic value"],
  },
  {
    id: "ds-003",
    name: "Franchise Pest Control Business - NJ",
    source: "dealstream",
    askingPrice: 675_000,
    revenue: 550_000,
    cashFlow: 200_000,
    ebitdaMargin: 36,
    multiple: 3.4,
    location: "New Jersey",
    state: "NJ",
    employees: 8,
    yearEstablished: 2016,
    recurringRevenuePct: 80,
    ownerInvolved: true,
    description: "Highly successful and well-established popular outdoor pest control franchise. Team of well-trained dedicated technicians servicing both commercial and residential properties. Specialized outdoor/mosquito and pest control operation.",
    url: "https://dealstream.com/d/biz-sale/pest-control/atj3q6",
    dateFound: "2026-03-21",
    status: "new",
    tags: ["franchise", "mosquito specialist", "trained team", "NJ market"],
  },
  // ── LoopNet listing ──
  {
    id: "ln-001",
    name: "Established Pest Control - Strong Recurring Revenue",
    source: "loopnet",
    askingPrice: 7_000_000,
    revenue: 7_000_000,
    cashFlow: 2_000_000,
    ebitdaMargin: 29,
    multiple: 3.5,
    location: "NYC Metro Area, NY",
    state: "NY",
    employees: 40,
    yearEstablished: 2000,
    recurringRevenuePct: 75,
    ownerInvolved: true,
    description: "Cross-listed from DealStream. Established pest control business with strong recurring revenue. $7M revenue, ~$2M EBITDA. Major platform acquisition opportunity for well-capitalized buyer.",
    url: "https://www.loopnet.com/biz/business-opportunity/established-pest-control-business-with-strong-recurring-revenue/2452122/",
    dateFound: "2026-03-22",
    status: "new",
    tags: ["large platform", "cross-listed", "LoopNet verified"],
  },
  // ── BizQuest listing ──
  {
    id: "bq-001",
    name: "Termite & Pest Control - 1,000+ Contracts - NJ",
    source: "bizquest",
    askingPrice: 500_000,
    revenue: 400_000,
    cashFlow: 180_000,
    ebitdaMargin: 45,
    multiple: 2.8,
    location: "Camden County, NJ",
    state: "NJ",
    employees: 4,
    yearEstablished: 1986,
    recurringRevenuePct: 90,
    ownerInvolved: true,
    description: "Pest control company specializing in termite control. In business for 40 years. Over 1,000 residual/recurring contracts. Annual termite renewals provide ongoing revenue stability. Strong margins at 45% EBITDA.",
    url: "https://www.bizquest.com/pest-control-businesses-for-sale-in-new-jersey/",
    dateFound: "2026-03-17",
    status: "reviewing",
    tags: ["40yr track record", "1000+ contracts", "termite specialist", "high margins"],
  },
];

export const listings: Listing[] = rawListings.map((l) => {
  const breakdown = scoreListing(l);
  const revenueMultiple = +(l.askingPrice / l.revenue).toFixed(2);
  return { ...l, revenueMultiple, score: breakdown.total, scoreBreakdown: breakdown } as Listing;
});

export const offMarketLeads: OffMarketLead[] = [
  {
    id: "om-001",
    businessName: "ABC Pest Control",
    ownerName: "Robert Marinelli",
    phone: "(201) 555-0142",
    address: "847 Main St",
    city: "Hackensack",
    state: "NJ",
    rating: 4.6,
    reviewCount: 187,
    yearsInBusiness: 28,
    estimatedRevenue: "$1.2M-$1.8M",
    ownerAge: "65+",
    source: "google_maps",
    outreachStatus: "not_contacted",
    notes: "Long-established business, family-run. Website hasn't been updated since 2019. Classic succession candidate.",
    lastUpdated: "2026-03-20",
    priorityScore: 92,
  },
  {
    id: "om-002",
    businessName: "Reliable Exterminating Co",
    ownerName: "Frank DeLuca",
    phone: "(914) 555-0198",
    address: "1220 Central Park Ave",
    city: "Yonkers",
    state: "NY",
    rating: 4.4,
    reviewCount: 253,
    yearsInBusiness: 35,
    estimatedRevenue: "$2.0M-$2.8M",
    ownerAge: "70+",
    source: "google_maps",
    outreachStatus: "contacted",
    notes: "High review volume indicates large customer base. Business established 1991. No succession plan visible. Second-generation owner nearing retirement.",
    lastUpdated: "2026-03-18",
    priorityScore: 95,
  },
  {
    id: "om-003",
    businessName: "Garden State Bug Busters",
    ownerName: "Anthony Russo",
    phone: "(973) 555-0167",
    address: "56 Bloomfield Ave",
    city: "Montclair",
    state: "NJ",
    rating: 4.8,
    reviewCount: 312,
    yearsInBusiness: 22,
    estimatedRevenue: "$1.5M-$2.2M",
    ownerAge: "60+",
    source: "license_db",
    outreachStatus: "responded",
    notes: "Found via NJ DEP pesticide license database. License holder since 2004. High Google rating in affluent market. Responded positively to initial outreach - interested in discussing options.",
    lastUpdated: "2026-03-22",
    priorityScore: 97,
  },
  {
    id: "om-004",
    businessName: "Stamford Pest Solutions",
    ownerName: "William Chen",
    phone: "(203) 555-0134",
    address: "199 Atlantic St",
    city: "Stamford",
    state: "CT",
    rating: 4.5,
    reviewCount: 145,
    yearsInBusiness: 18,
    estimatedRevenue: "$800K-$1.2M",
    ownerAge: "55-60",
    source: "association",
    outreachStatus: "not_contacted",
    notes: "Found via CT Pest Control Association membership directory. Active member since 2008. Smaller operation but excellent location for CT market entry.",
    lastUpdated: "2026-03-19",
    priorityScore: 78,
  },
  {
    id: "om-005",
    businessName: "Borough Pest Management",
    ownerName: "James O'Brien",
    phone: "(718) 555-0156",
    address: "3421 Broadway",
    city: "Bronx",
    state: "NY",
    rating: 4.3,
    reviewCount: 98,
    yearsInBusiness: 31,
    estimatedRevenue: "$900K-$1.4M",
    ownerAge: "65+",
    source: "google_maps",
    outreachStatus: "not_contacted",
    notes: "Urban specialist. Long tenure suggests stable customer base. Lower review count may indicate less tech-savvy owner (opportunity for modernization). Website is basic HTML from early 2000s.",
    lastUpdated: "2026-03-21",
    priorityScore: 84,
  },
  {
    id: "om-006",
    businessName: "Suburban Shield Pest Co",
    ownerName: "Thomas Kowalski",
    phone: "(516) 555-0189",
    address: "2100 Hempstead Tpke",
    city: "East Meadow",
    state: "NY",
    rating: 4.7,
    reviewCount: 224,
    yearsInBusiness: 25,
    estimatedRevenue: "$1.8M-$2.5M",
    ownerAge: "60+",
    source: "google_maps",
    outreachStatus: "meeting_set",
    notes: "Large Long Island operation. High review count and rating. Found through Google Maps scrape - website mentions 'family owned since 2001'. Meeting scheduled for March 28.",
    lastUpdated: "2026-03-23",
    priorityScore: 94,
  },
  {
    id: "om-007",
    businessName: "Pro-Tech Pest Elimination",
    ownerName: "Michael Santoro",
    phone: "(908) 555-0143",
    address: "789 Route 22",
    city: "Bridgewater",
    state: "NJ",
    rating: 4.2,
    reviewCount: 167,
    yearsInBusiness: 20,
    estimatedRevenue: "$1.0M-$1.5M",
    ownerAge: "60+",
    source: "referral",
    outreachStatus: "contacted",
    notes: "Referred by SBA lender contact. Owner has mentioned retirement plans at industry events. Central NJ location good for route density with existing NJ targets.",
    lastUpdated: "2026-03-17",
    priorityScore: 88,
  },
  {
    id: "om-008",
    businessName: "Valley Pest Professionals",
    ownerName: "Richard Patel",
    phone: "(845) 555-0172",
    address: "445 Route 9W",
    city: "Newburgh",
    state: "NY",
    rating: 4.5,
    reviewCount: 89,
    yearsInBusiness: 15,
    estimatedRevenue: "$600K-$900K",
    ownerAge: "55-60",
    source: "google_maps",
    outreachStatus: "not_interested",
    notes: "Hudson Valley operator. Responded to outreach but says not interested in selling at this time. Worth following up in 6-12 months.",
    lastUpdated: "2026-03-15",
    priorityScore: 55,
  },
];
